### ISSUE TITLE
install iconv error

### ISSUE THREAD

**Issue by lemig** [bda-research/node-crawler#104]
Hi,

This is the error I get when I install the package:

```
$ npm install crawler

> contextify@0.1.8 install /Users/miguel/legeant_crawler/node_modules/crawler/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/contextify.node
  SOLINK_MODULE(target) Release/contextify.node: Finished

> iconv@2.1.4 install /Users/miguel/legeant_crawler/node_modules/crawler/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
cc1: error: unrecognized command line option "-Wno-parentheses-equality"
cc1: error: unrecognized command line option "-Wno-static-in-inline"
cc1: error: unrecognized command line option "-Wno-tautological-compare"
make: *** [Release/obj.target/libiconv/deps/libiconv/lib/iconv.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/miguel/legeant_crawler/node_modules/crawler/node_modules/iconv
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing iconv@2.1.4
crawler@0.2.6 node_modules/crawler
├── generic-pool@2.1.1
├── underscore@1.6.0
├── htmlparser@1.7.7
├── iconv-lite@0.4.4
├── jschardet@1.1.0
├── compression@1.0.9 (vary@0.1.0, on-headers@0.0.0, bytes@1.0.0, compressible@1.1.0, accepts@1.0.7, debug@1.0.4)
├── request@2.39.0 (json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, qs@0.6.6, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.0, node-uuid@1.4.1, mime-types@1.0.1, form-data@0.1.4, tough-cookie@0.12.1, http-signature@0.10.0, hawk@1.1.1)
├── jsdom@0.10.6 (xmlhttprequest@1.6.0, cssom@0.3.0, nwmatcher@1.3.3, htmlparser2@3.7.3, contextify@0.1.8, cssstyle@0.2.14)
└── qunit@0.6.4 (tracejs@0.1.8, argsparser@0.0.6, cli-table@0.3.0, qunitjs@1.10.0, istanbul@0.2.16)
```

**Comment by mike442144** [comment]
@marcosantana77 we remove native iconv module, and use iconv-lite instead in new version.
