### ISSUE TITLE
TypeError  undefined is not a function

### ISSUE THREAD

**Issue by aalireza439** [bda-research/node-crawler#150]
here is code is used.(it's on readme).
```
var Crawler = require("crawler");
var url = require('url');

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, result, $) {
        // $ is Cheerio by default
        //a lean implementation of core jQuery designed specifically for the server
        $('a').each(function(index, a) {
            var toQueueUrl = $(a).attr('href');
            c.queue(toQueueUrl);
        });
    }
});

// Queue just one URL, with default callback
c.queue('http://joshfire.com');
```

i got this error : 
```
TypeError: undefined is not a function
    at Object.Crawler.callback (/home/app/app.js:10:9)
    at Crawler._onContent (/home/app/node_modules/crawler/lib/crawler.js:461:17)
    at Request._callback (/home/app/node_modules/crawler/lib/crawler.js:351:18)
    at Request.self.callback (/home/app/node_modules/crawler/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/app/node_modules/crawler/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/app/node_modules/crawler/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```
node.js version i use : v0.10.37

**Comment by mike442144** [comment]
Maybe you should check if there is an error first. As I got time out error when I visit http://joshfire.com/

**Comment by sarkhanbayramli** [comment]
I keep getting the same and in callback function I check for error. Any ideas?

**Comment by mike442144** [comment]
@sarkhanbayramli Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.
