### ISSUE TITLE
skipDuplicate: true blocked scanning

### ISSUE THREAD

**Issue by jacopocappelli1989** [bda-research/node-crawler#164]
With SkipDuplicate option i see that scanned url remain blocked and onDrain not called.
If i set to false all work well, where am I wrong?

Thanks,
Jacopo

**Comment by mike442144** [comment]
Hi guy, what do you mean by remain blocked? Maybe there is bug in `skipDuplicate` option, I'll check it.

**Comment by brandonros** [comment]
There is.

```
var crawler = require('crawler');

var c = new crawler({
	maxConnections: 5,
	callback: function (err, res, $) {
		$('a').each(function (index, a) {
			var url = $(a).attr('href');

			c.queue(url);
		});
	},
	onDrain: function () {
		console.log(arguments);
	},
	skipDuplicates: true
});

c.queue('https://google.com');
```

```
➜  ~  node crawl.js
/Users/Marketing/node_modules/crawler/node_modules/generic-pool/lib/generic-pool.js:341
    var objWithTimeout = { obj: obj, timeout: (new Date().getTime() + idleTimeoutMillis) };
    ^

RangeError: Maximum call stack size exceeded
    at Object.me.release (/Users/Marketing/node_modules/crawler/node_modules/generic-pool/lib/generic-pool.js:341:5)
    at Crawler._release (/Users/Marketing/node_modules/crawler/lib/crawler.js:125:19)
    at Crawler.<anonymous> (/Users/Marketing/node_modules/crawler/lib/crawler.js:110:14)
    at emitOne (events.js:77:13)
    at Crawler.emit (events.js:169:7)
    at Crawler._onContent (/Users/Marketing/node_modules/crawler/lib/crawler.js:382:21)
    at Request._callback (/Users/Marketing/node_modules/crawler/lib/crawler.js:327:25)
    at self.callback (/Users/Marketing/node_modules/crawler/node_modules/request/request.js:236:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
```

**Comment by brandonros** [comment]
Nevermind. My issue was related to the handling of links that start with `//` instead of `http://` or `https://`

**Comment by mike442144** [comment]
@brandonros Okay. It's better to use [seenreq](https://github.com/mike442144/seenreq#options) to skip duplicate. And as to the `crawler`, please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it. I'll continue to make it the best crawler in nodejs world.

**Comment by mike442144** [comment]
Close due to inactive.
