### ISSUE TITLE
Nodejs gives me the following error

### ISSUE THREAD

**Issue by limeblack** [bda-research/node-crawler#171]
I get the following error in nodejs.

```
        $('a').each(function(index, a) {
        ^

TypeError: $ is not a function
    at Object.Crawler.callback (C:\Users\a\Desktop\crawler.js:10:9)
    at Crawler._onContent (C:\Users\a\node_modules\crawler\lib\crawler.js:461:17
)
    at Request._callback (C:\Users\a\node_modules\crawler\lib\crawler.js:351:18)

    at Request.self.callback (C:\Users\a\node_modules\crawler\node_modules\reque
st\request.js:236:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\a\node_modules\crawler\node_modules\request
\request.js:1142:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\a\node_modules\crawler\node_modules
\request\request.js:1096:12)

C:\Users\a\Desktop>node crawler.js
C:\Users\a\node_modules\crawler\lib\crawler.js:295
    var ropts = JSON.parse(JSON.stringify(options));
                                ^

RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at Crawler._buildHTTPRequest (C:\Users\a\node_modules\crawler\lib\crawler.js
:295:33)
    at Crawler._executeCrawlerRequest (C:\Users\a\node_modules\crawler\lib\crawl
er.js:278:14)
    at Crawler._makeCrawlerRequest (C:\Users\a\node_modules\crawler\lib\crawler.
js:258:14)
    at C:\Users\a\node_modules\crawler\lib\crawler.js:245:18
    at dispense (C:\Users\a\node_modules\crawler\node_modules\generic-pool\lib\g
eneric-pool.js:250:16)
    at Object.me.release (C:\Users\a\node_modules\crawler\node_modules\generic-p
ool\lib\generic-pool.js:349:5)
    at Crawler._release (C:\Users\a\node_modules\crawler\lib\crawler.js:125:19)
    at Crawler.<anonymous> (C:\Users\a\node_modules\crawler\lib\crawler.js:110:1
4)
    at emitOne (events.js:77:13)
    at Crawler.emit (events.js:169:7)

```

and the following code

```
var Crawler = require("crawler");
var url = require('url');

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, result, $) {
        // $ is Cheerio by default
        //a lean implementation of core jQuery designed specifically for the server
        $('a').each(function(index, a) {
            var toQueueUrl = $(a).attr('href');
            c.queue(toQueueUrl);
        });
    }
});

// Queue just one URL, with default callback
c.queue('http://google.com');
```

**Comment by mike442144** [comment]
Hi, 
Which type of Error you got:

1. TypeError: $ is not a function
2. RangeError: Maximum call stack size exceeded

or both?
For the first one, please do check if `$` exists, since it is `undefined` if the page type is not `text/html`.
The second means cycle reference in the options.

**Comment by Viltaria** [comment]
I get the same error, did you ever find out how to fix it? @limeblack

**Comment by Viltaria** [comment]
@mike442144 $ did exist for me, when I log it I get

```
{ [Function]
  load: [Function],
  html: [Function],
  xml: [Function],
  text: [Function],
  parseHTML: [Function],
  root: [Function],
  contains: [Function],
  _root: 
   { type: 'root',
     name: 'root',
     attribs: {},
     children: [ [Object], [Object], [Object], [Object] ],
     next: null,
     prev: null,
     parent: null },
  _options: 
   { normalizeWhitespace: false,
     xmlMode: false,
     decodeEntities: true,
     withDomLvl1: true } }
```

but I still get the same error as he did above, not the second one though.

**Comment by bunopus** [comment]
I have same error on empty project

**Comment by Viltaria** [comment]
@bunopus Thanks!

**Comment by mike442144** [comment]
@Viltaria We are going to remove the sample in next release, because it is totally an error guidance.

**Comment by loretoparisi** [comment]
I get the same error on the same code not at every execution:

```
$('a').each(function(index, a) {
        ^

TypeError: $ is not a function
```

**Comment by mike442144** [comment]
Please use the new version instead.

**Comment by loretoparisi** [comment]
@mike442144 yes there are two npm modules, the right one is:

```javascript
/**
 * @see https://github.com/bda-research/node-webcrawler
 */
var Crawler = require("node-webcrawler");
```

and than as stated above you may want do to like:

```javascript
/**
     * Parse string to HTML struct
     * @param html String of html
     * @param block completion block
     */
    Parser.prototype.parse = function(html,block) {
      var self=this;
      try {
        var $ = cheerio.load(html);
        return block.apply(this,[$]);
      } catch (e) {
        return new Error(e);
      }
    } //parse
```

in order to separate `cheerio` as DOM loader from the `html` string, so that you do:

```javascript
// Queue URLs with custom callbacks & parameters
            // parameters will override default options
            self.crawler.queue([{
                userAgent: self.browser.userAgent() || self.options.crawler.userAgent,
                cache: true,
                uri: params.url,
                jQuery: {
                    name: 'cheerio',
                    options: {
                        //normalizeWhitespace: true,
                        xmlMode: false
                    }
                },
// The global callback won't be called
                callback: function (error, result, $) {
//...
            self.parser.parse(result.body, function($) {

           // safely use $ here
         });

   }
            }]);
```

**Comment by darrenqc** [comment]
@limeblack please use the latest version, node-crawler@1.0.1

A sample code will be like:
```
crawler.queue({
    uri:'http://www.google.com',
    jQuery:true,
    callback:function(err, res, done) {
        if(err)
            return console.log(err)
        // if response content-type is not html, $ will not be injected into res, which means res.$ = undefined
        if(res.$) {
            // do things you want to do with $ here
            ...
        }
    }
})
```

I assume that you are using node-crawler@0.4.0, In that case, if one of the following conditions are met, $ will be undefined:

1. jQuery is set false
2. response.body does not start with '<html'

The conclusion is you have to check if `$` exists before you use it, just like you should check if `error` exists before you proceed.
