### ISSUE TITLE
Timeout Error From enqueue Module

### ISSUE THREAD

**Issue by JesusIslam** [bda-research/node-crawler#180]
Got this error while running my crawler:

```
Failed to get item description: Error: job timed out
    at Timeout.<anonymous> (/home/dida/zaloracrawler/node_modules/enqueue/index.js:65:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Any pointer? The timeout value for the crawler is the default 60000.

**Comment by JesusIslam** [comment]
nvm, it is actually the other package that causes this. Sorry.
