### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#200]
# 1、mac os 10.12.3
# 2、$ node -v
v7.7.1
# 3、
```
$ npm info crawler
 
{ name: 'crawler',
  description: 'Crawler is a web spider written with Nodejs. It gives you the full power of jQuery on the server to parse a big number of pages as they are downloaded, asynchronously',
  'dist-tags': { latest: '1.0.3', beta: '1.0.0' },
  versions: 
   [ '0.0.1',
     '0.0.2',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.7',
     '0.3.0',
     '0.3.1',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3' ],
  maintainers: 
   [ 'darrenqc <darrenqc823@gmail.com>',
     'mike442144 <mike442144@hotmail.com>',
     'paulvalla <bonjour@pol.ninja>',
     'sylvinus <sylvain@sylvainzimmer.com>' ],
  repository: 
   { type: 'git',
     url: 'git+https://github.com/bda-research/node-crawler.git' },
  time: 
   { '0.2.0': '2012-12-06T16:07:37.238Z',
     modified: '2017-02-28T09:21:16.128Z',
     created: '2012-09-10T08:41:01.230Z',
     '0.0.1': '2012-09-10T08:41:01.230Z',
     '0.0.2': '2012-09-10T08:41:01.230Z',
     '0.2.1': '2012-12-06T21:31:17.775Z',
     '0.2.2': '2012-12-09T19:18:13.728Z',
     '0.2.3': '2013-02-22T08:55:39.932Z',
     '0.2.4': '2013-02-26T14:57:36.485Z',
     '0.2.5': '2013-08-01T16:14:29.802Z',
     '0.2.6': '2014-07-04T08:23:19.072Z',
     '0.2.7': '2014-09-04T08:08:06.445Z',
     '0.3.0': '2014-10-22T00:43:17.165Z',
     '0.3.1': '2014-10-23T06:00:02.473Z',
     '0.4.0': '2014-11-08T03:19:51.793Z',
     '0.4.1': '2014-11-14T05:53:37.073Z',
     '0.4.2': '2015-02-20T00:56:09.988Z',
     '0.4.3': '2015-03-17T00:54:46.102Z',
     '1.0.0': '2016-12-01T10:50:43.686Z',
     '1.0.1': '2016-12-09T14:14:35.561Z',
     '1.0.2': '2017-01-03T03:50:57.747Z',
     '1.0.3': '2017-02-21T05:33:21.175Z' },
  users: 
   { devonning: true,
     pana: true,
     mayorova: true,
     timothykrell: true,
     villadora: true,
     ecilteodoro: true,
     developerworks: true,
     googya: true,
     yi: true,
     jculvey: true,
     astro: true,
     benjamins: true,
     etiv: true,
     acarlos1000: true,
     eterna2: true,
     mares29: true,
     fissl: true,
     edum1978: true,
     mecal: true,
     tiger2wander: true,
     mimmo1: true,
     rkielty: true,
     scl33: true,
     womjoy: true,
     leonning: true,
     me6iaton: true,
     stany: true,
     kulakowka: true,
     parties: true,
     anmol1771: true,
     tomjamescn: true,
     'yoshimaa-tricot': true,
     moimikey: true,
     wangnan0610: true,
     ahmadazimi: true,
     mastayoda: true,
     joeyblue: true,
     davidrc: true,
     pdedkov: true,
     dragonken: true,
     skrdv: true,
     kparkov: true,
     'esraa-ammar': true,
     fpmweb: true,
     ineva: true,
     '8legged': true,
     dainov: true,
     diegoperini: true,
     jerrywu: true,
     nuer: true,
     ahvonenj: true,
     yanqirenshi: true,
     hugohua: true,
     zafaransari: true,
     hsian: true },
  keywords: 
   [ 'dom',
     'javascript',
     'crawling',
     'spider',
     'scraper',
     'scraping',
     'jquery',
     'crawler',
     'nodejs' ],
  bugs: { url: 'https://github.com/bda-research/node-crawler/issues' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/bda-research/node-crawler',
  version: '1.0.3',
  main: './lib/crawler.js',
  directories: { test: 'tests' },
  scripts: { test: './node_modules/mocha/bin/mocha --reporter spec --bail --timeout 10000 tests/*.js' },
  'engine-strict': { node: '>=4.0.0' },
  dependencies: 
   { bottleneckp: '~1.1.0',
     'charset-parser': '^0.2.0',
     cheerio: '^0.22.0',
     'iconv-lite': '^0.4.8',
     lodash: '^4.17.4',
     request: '~2.79.0',
     seenreq: '^0.1.7',
     'type-is': '^1.6.14' },
  devDependencies: 
   { chai: '^2.3.0',
     jsdom: '^9.6.0',
     mocha: '^2.2.5',
     'mocha-testdata': '^1.1.0',
     sinon: '^1.14.1',
     whacko: '^0.19.1' },
  licenses: 
   [ { type: 'MIT',
       url: 'http://github.com/bda-research/node-crawler/blob/master/LICENSE.txt' } ],
  gitHead: 'e7b8db60256e22bdd26907d7794b5677fa9afa5e',
  dist: 
   { shasum: 'a923a752d68097f2727a28e1352c44c05941cc60',
     tarball: 'https://registry.npmjs.org/crawler/-/crawler-1.0.3.tgz' } }

```
#4 、code
```
var Crawler = require("crawler");
function fnDoGetUrl(url, fncbk)
{
	//** 从百度爬取
var g_c = new Crawler({
    maxConnections : 1000,
    callback : function (e, r, $) 
    {
    	this.fncbk(e, r, $);
    }
});
	g_c.queue({userAgent:"Mozilla/5.0 (Macintosh; Linux) AppleWebKit/9999.36 (KHTML, like Gecko) Chrome/99.0.2062.94 Safari/9999.36",
  	"uri": url,
  	"fncbk":fncbk
	});
}
```

#5、
```
/usr/local/lib/node_modules/crawler/crawler.js:47
		Object.observe(that.stopped, (changes)=>{
		       ^

TypeError: Object.observe is not a function
    at new Crawler (/usr/local/lib/node_modules/crawler/crawler.js:47:10)
    at fnDoGetUrl (/Users/xiatian/safe/nodeJs/crawler/myInfoNew.js:195:11)
    at getIp (/Users/xiatian/safe/nodeJs/crawler/myInfoNew.js:224:2)
    at Object.<anonymous> (/Users/xiatian/safe/nodeJs/crawler/myInfoNew.js:106:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

```

**Comment by hktalent** [comment]
# do ....is ok
```
npm uninstall -g crawler
npm install -g crawler
and
call code after fnDoGetUrl
```
so is ok
