### ISSUE TITLE
how to set proxy

### ISSUE THREAD

**Issue by InSpirit12** [bda-research/node-crawler#202]
i can crawling without proxy at the same machine, but when i want to use proxy crawing something with this format:
`
c.queue({
    uri:'http://www.somewebsite.com/page/1',
    proxy:'ipaddr:port'
})
`
nothing happened, the request can not be sent normally, Is the format correct?
the error log is:
`
Error: Invalid URI "/"
    at Request.init (/home/djn_workspace/spider/node_modules/request/request.js:274:31)
    at new Request (/home/djn_workspace/spider/node_modules/request/request.js:128:8)
    at request (/home/djn_workspace/spider/node_modules/request/index.js:54:10)
    at Crawler._buildHTTPRequest (/home/djn_workspace/spider/node_modules/crawler/lib/crawler.js:303:5)
    at /home/djn_workspace/spider/node_modules/crawler/lib/crawler.js:229:18
    at Timeout._onTimeout (/home/djn_workspace/spider/node_modules/bottleneckp/lib/Bottleneck.js:120:13)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
`

**Comment by mike442144** [comment]
Plus protocol, like `http://` or `https://`

**Comment by liyinchigithub** [comment]
@mike442144 

I have a problem

`c.queue([{
    uri: 'https://www.youtube.com/channel/UCg5LAj2B_Zs_FgqUOMrCMiQ/videos', //你想爬取的网页链接.
    proxy:'http://192.168.31.81:1087'
]})
`

when fetching https://www.youtube.com/channel/UCg5LAj2B_Zs_FgqUOMrCMiQ/videos (3 retries left)

**Comment by mike442144** [comment]
You mean the video stream? I'm afraid crawler is not for the scenario.
