### ISSUE TITLE
how catch it

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#205]
Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/crawler/node_modules/request/request.js:813:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', connect: true

**Comment by mike442144** [comment]
You should always see if error each time in a callback:

```
function(err, res, done){
    if(err){
        console.error(err);
    }
}
```
