### ISSUE TITLE
res can not support stream pipe: fs.createWriteStream(res.options.filename).pipe(res);

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#313]
```
callback:function(err, res, done){
        if(err){
            console.error(err.stack);
        }else{
            fs.createWriteStream(res.options.filename).pipe(res);
        }
        
        done();
    }
```
https://github.com/hktalent/webcrawler/issues/1

### ???
```
res.pipe(fs.createWriteStream(res.options.filename));
```

**Comment by mike442144** [comment]
Need more details.

**Comment by hktalent** [comment]
@mike442144 
```
buffer.js:224
throw err;
^

RangeError: "size" argument must not be larger than 2147483647
at Function.Buffer.allocUnsafe (buffer.js:253:3)
at Function.Buffer.concat (buffer.js:441:23)
at Request. /webcrawler/node_modules/request/request.js:1133:30)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at IncomingMessage. webcrawler/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
```

**Comment by mike442144** [comment]
No enough information.

**Comment by sanriqing** [comment]
Hey, buddy, how did you end up solving this problem？I was trying to download some pictures and I got the same problem。。。。

**Comment by mike442144** [comment]
@sanriqing Pls refer to [Download Images and Other Files](https://github.com/bda-research/node-crawler/tree/master/examples#download-images-and-other-files)
