### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by maciejjankowski** [bda-research/node-crawler#69]
```
D:\node\polgastro\node_modules\crawler\lib\crawler.js:296
                          if (callbackError) throw callbackError;
                                                   ^
TypeError: undefined is not a function
    at Object.Crawler.callback (D:\node\polgastro\crawlr.js:10:3)
    at jsdom.env.done (D:\node\polgastro\node_modules\crawler\lib\crawler.js:272:41)
    at D:\node\polgastro\node_modules\crawler\node_modules\jsdom\lib\jsdom.js:252:9
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by aalireza439** [comment]
i have same issues . node.js version i use : v0.10.37

**Comment by rahul-desai3** [comment]
Same issue here with node.js v4.1.1
