### ISSUE TITLE
Option request.jar is broken

### ISSUE THREAD

**Issue by 1602** [bda-research/node-crawler#72]
```
var r = require('crawler/node_modules/request');
var Crawler = require('crawler').Crawler;

var crawler = new Crawler({jar: r.jar()});
crawler.queue({
    uri: 'http://github.com',
    callback: test
}, {
    uri: 'http://gitcities.com',
    callback: test
});

function test(err, res) {
    console.log(res.headers);
}
```

throws

```
Object #<Object> has no method 'get'
TypeError: Object #<Object> has no method 'get'
    at Request.jar (/Users/anatoliy/projects/opensource/node-crawler/node_modules/request/index.js:1139:19)
    at Request.init (/Users/anatoliy/projects/opensource/node-crawler/node_modules/request/index.js:227:8)
    at new Request
(skipped rest of stacktrace)
```

I will send pull request as we need it published asap. Thanks!

**Comment by mike442144** [comment]
fixed in new version.if you have questions, just reopen it.
